server:
  port: 7000

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/animal
    #    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate:
      SQL: debug

